M48
; DRILL file {KiCad (6.0.8)} date Mon Oct 31 22:25:23 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-31T22:25:23+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X5.2251Y-4.4401
X5.2251Y-5.1999
X7.4149Y-4.4401
X7.4149Y-5.1999
T0
M30
